dropout: 0.3
dropatt: 0.3
lr: 0.001
batch_size: 32
d_inner: 1028
d_model: 400
n_head: 8
d_head: 50
pitch_emsize: 64
dur_emsize: 64
offset_emsize: 16
n_layer: 4
save_name: model
tgt_len: 64
eval_tgt_len: 64
mem_len: 64
#fp16: True
optim: ranger
max_step: 500000